name: e-library-backend
region: fra
services:
  - name: web
    environment_slug: python
    github:
      branch: main
      deploy_on_push: true
      repo: IbroIT/e-library-front
    source_dir: /backend
    run_command: gunicorn backend.wsgi --log-file -
    build_command: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate --noinput
    http_port: 8000
    instance_count: 1
    instance_size_slug: basic-xxs
    envs:
      - key: SECRET_KEY
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: DEBUG
        value: "False"
        scope: RUN_AND_BUILD_TIME
      - key: ALLOWED_HOSTS
        value: "${APP_DOMAIN},${_self.ONDIGITALOCEAN_APP_URL}"
        scope: RUN_AND_BUILD_TIME
      - key: CORS_ALLOWED_ORIGINS
        value: "https://su-e-library.vercel.app,https://su-library.com"
        scope: RUN_AND_BUILD_TIME
      - key: DATABASE_URL
        value: "${db.DATABASE_URL}"
        scope: RUN_AND_BUILD_TIME
      - key: DJANGO_SETTINGS_MODULE
        value: "backend.settings"
        scope: RUN_AND_BUILD_TIME
      # DigitalOcean Spaces для статических и медиа файлов
      - key: USE_SPACES
        value: "True"
        scope: RUN_AND_BUILD_TIME
      - key: AWS_ACCESS_KEY_ID
        value: "DO801328JW7UKUFKDWJJ"
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: AWS_SECRET_ACCESS_KEY
        value: "MeSNvR1wHHPs8CLI1f0aaNhYjxLnQ7YRyS+QeHDDSZs"
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: AWS_STORAGE_BUCKET_NAME
        value: "su-library"
        scope: RUN_AND_BUILD_TIME
      - key: AWS_S3_ENDPOINT_URL
        value: "https://blr1.digitaloceanspaces.com"
        scope: RUN_AND_BUILD_TIME
      - key: AWS_S3_REGION_NAME
        value: "blr1"
        scope: RUN_AND_BUILD_TIME
      - key: AWS_S3_CUSTOM_DOMAIN
        value: "su-library.blr1.digitaloceanspaces.com"
        scope: RUN_AND_BUILD_TIME

databases:
  - name: db
    engine: PG
    version: "12"
    production: false
    cluster_name: e-library-db-cluster
