# Generated by Django 5.1.2 on 2025-11-04 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_booktranslation_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='books/covers/%Y/%m/%d/', verbose_name='Обложка книги'),
        ),
    ]
