# Generated by Django 5.1.2 on 2025-11-07 08:09

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_book_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, storage=main.models.get_media_storage, upload_to='books/covers/%Y/%m/%d/', verbose_name='Обложка книги'),
        ),
        migrations.AlterField(
            model_name='book',
            name='pdf_file',
            field=models.FileField(storage=main.models.get_media_storage, upload_to='books/pdfs/%Y/%m/%d/', verbose_name='PDF файл'),
        ),
    ]
