# Generated by Django 6.0.2 on 2026-02-07 14:52

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_book_cover_image_alter_book_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='books/covers/%Y/%m/%d/', validators=[main.models.validate_image_file_size], verbose_name='Обложка книги'),
        ),
        migrations.AlterField(
            model_name='book',
            name='pdf_file',
            field=models.FileField(upload_to='books/pdfs/%Y/%m/%d/', validators=[main.models.validate_pdf_file_size], verbose_name='PDF файл'),
        ),
    ]
